name: flutter_progress
description: Highly customizable and light weight progress library including dynamic updates
repository: https://github.com/Bungeefan/flutter_progress
version: 1.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
